### ISSUE TITLE
Doesn't compile with ESPHome esphome-2022.3.0b1

### ISSUE THREAD

**Issue by SeByDocKy** [syssi/esphome-jk-bms#56]
According to jessierocks, need some update :  https://github.com/esphome/esphome/pull/3216
``` PS C:\Users\SeByDocKy\Desktop\SeBy\Maison\Home assistant\47> esphome run pvbrain.yaml
←[32mINFO Reading configuration pvbrain.yaml...←[0m
←[32mINFO Updating https://github.com/syssi/esphome-jk-bms.git@main←[0m
←[31mERROR Unable to load component pipsolar.sensor:
Traceback (most recent call last):
  File "C:\Users\SeByDocKy\anaconda3\lib\site-packages\esphome\loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "C:\Users\SeByDocKy\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\SeByDocKy\Desktop\SeBy\Maison\Home assistant\47\my_components\pipsolar\sensor\__init__.py", line 85, in <module>
    CONF_GRID_RATING_VOLTAGE: sensor.sensor_schema(
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 4 were given←[0m
←[31mERROR Unable to load component jk_bms.sensor:
Traceback (most recent call last):
  File "C:\Users\SeByDocKy\anaconda3\lib\site-packages\esphome\loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "C:\Users\SeByDocKy\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\SeByDocKy\Desktop\SeBy\Maison\Home assistant\47\.esphome\external_components\35bd8a5b\components\jk_bms\sensor.py", line 225, in <module>
    cv.Optional(CONF_MIN_CELL_VOLTAGE): sensor.sensor_schema(
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 5 were given←[0m
←[32mINFO Detected timezone 'Europe/Paris'←[0m
Failed config

sensor.pipsolar: [source pvbrain.yaml:587]

  Platform not found: 'sensor.pipsolar'.
  platform: pipsolar
  pipsolar_id: pip8048
  grid_rating_voltage:
    id: pvbrain_axpert_grid_rating_voltage
    name: pvbrain_axpert_grid_rating_voltage
  grid_rating_current:
    id: pvbrain_axpert_grid_rating_current
    name: pvbrain_axpert_grid_rating_current
  ac_output_rating_voltage:
    id: pvbrain_axpert_ac_output_rating_voltage
    name: pvbrain_axpert_ac_output_rating_voltage
  ac_output_rating_frequency:
    id: pvbrain_axpert_ac_output_rating_frequency
    name: pvbrain_axpert_ac_output_rating_frequency
  ac_output_rating_current:
    id: pvbrain_axpert_ac_output_rating_current
    name: pvbrain_axpert_ac_output_rating_current
  ac_output_rating_apparent_power:
    id: pvbrain_axpert_ac_output_rating_apparent_power
    name: pvbrain_axpert_ac_output_rating_apparent_power
  ac_output_rating_active_power:
    id: pvbrain_axpert_ac_output_rating_active_power
    name: pvbrain_axpert_ac_output_rating_active_power
  battery_rating_voltage:
    id: pvbrain_axpert_battery_rating_voltage
    name: pvbrain_axpert_battery_rating_voltage
  battery_recharge_voltage:
    id: pvbrain_axpert_battery_recharge_voltage
    name: pvbrain_axpert_battery_recharge_voltage
  battery_under_voltage:
    id: pvbrain_axpert_battery_under_voltage
    name: pvbrain_axpert_battery_under_voltage
  battery_bulk_voltage:
    id: pvbrain_axpert_battery_bulk_voltage
    name: pvbrain_axpert_battery_bulk_voltage
  battery_float_voltage:
    id: pvbrain_axpert_battery_float_voltage
    name: pvbrain_axpert_battery_float_voltage
  battery_type:
    id: pvbrain_axpert_battery_type
    name: pvbrain_axpert_battery_type
  battery_redischarge_voltage:
    id: pvbrain_axpert_battery_redischarge_voltage
    name: pvbrain_axpert_battery_redischarge_voltage
  current_max_ac_charging_current:
    id: pvbrain_axpert_current_max_ac_charging_current
    name: pvbrain_axpert_current_max_ac_charging_current
  current_max_charging_current:
    id: pvbrain_axpert_current_max_charging_current
    name: pvbrain_axpert_current_max_charging_current
  output_source_priority:
    id: pvbrain_axpert_output_source_priority
    name: pvbrain_axpert_output_source_priority
  output_mode:
    id: pvbrain_axpert_output_mode
    name: pvbrain_axpert_output_mode
  output_load_percent:
    id: pvbrain_axpert_output_load_percent
    name: pvbrain_axpert_output_load_percent
  charger_source_priority:
    id: pvbrain_axpert_charger_source_priority
    name: pvbrain_axpert_charger_source_priority
  grid_voltage:
    id: pvbrain_axpert_grid_voltage
    name: pvbrain_axpert_grid_voltage
  grid_frequency:
    id: pvbrain_axpert_grid_frequency
    name: pvbrain_axpert_grid_frequency
  ac_output_voltage:
    id: pvbrain_axpert_ac_output_voltage
    name: pvbrain_axpert_ac_output_voltage
  ac_output_frequency:
    id: pvbrain_axpert_ac_output_frequency
    name: pvbrain_axpert_ac_output_frequency
  ac_output_apparent_power:
    id: pvbrain_axpert_ac_output_apparent_power
    name: pvbrain_axpert_ac_output_apparent_power
  ac_output_active_power:
    id: pvbrain_axpert_ac_output_active_power
    name: pvbrain_axpert_ac_output_active_power
  bus_voltage:
    id: pvbrain_axpert_bus_voltage
    name: pvbrain_axpert_bus_voltage
  battery_voltage:
    id: pvbrain_axpert_battery_voltage
    name: pvbrain_axpert_battery_voltage
  battery_charging_current:
    id: pvbrain_axpert_battery_charging_current
    name: pvbrain_axpert_battery_charging_current
  battery_capacity_percent:
    id: pvbrain_axpert_battery_capacity_percent
    name: pvbrain_axpert_battery_capacity_percent
  battery_voltage_scc:
    id: pvbrain_axpert_battery_voltage_scc
    name: pvbrain_axpert_battery_voltage_scc
  battery_discharge_current:
    id: pvbrain_axpert_battery_discharge_current
    name: pvbrain_axpert_battery_discharge_current
  battery_voltage_offset_for_fans_on:
    id: pvbrain_axpert_battery_voltage_offset_for_fans_on
    name: pvbrain_axpert_battery_voltage_offset_for_fans_on
  inverter_heat_sink_temperature:
    id: pvbrain_axpert_inverter_heat_sink_temperature
    name: pvbrain_axpert_inverter_heat_sink_temperature
  eeprom_version:
    id: pvbrain_axpert_eeprom_version
    name: pvbrain_axpert_eeprom_version
  pv1_input_current:
    id: pvbrain_axpert_pv1_input_current
    name: pvbrain_axpert_pv1_input_current
  pv1_input_voltage:
    id: pvbrain_axpert_pv1_input_voltage
    name: pvbrain_axpert_pv1_input_voltage
  pv1_charging_power:
    id: pvbrain_axpert_pv1_charging_power
    name: pvbrain_axpert_pv1_charging_power
  pv2_input_current:
    id: pvbrain_axpert_pv2_input_current
    name: pvbrain_axpert_pv2_input_current
  pv2_input_voltage:
    id: pvbrain_axpert_pv2_input_voltage
    name: pvbrain_axpert_pv2_input_voltage
  pv2_charging_power:
    id: pvbrain_axpert_pv2_charging_power
    name: pvbrain_axpert_pv2_charging_power
sensor.jk_bms: [source pvbrain.yaml:840]

  Platform not found: 'sensor.jk_bms'.
  platform: jk_bms
  min_cell_voltage:
    name: pvbrain_jkbms min cell voltage
  max_cell_voltage:
    name: pvbrain_jkbms max cell voltage
  delta_cell_voltage:
    name: pvbrain_jkbms delta cell voltage
  cell_voltage_1:
    name: pvbrain_jkbms cell voltage 1
  cell_voltage_2:
    name: pvbrain_jkbms cell voltage 2
  cell_voltage_3:
    name: pvbrain_jkbms cell voltage 3
  cell_voltage_4:
    name: pvbrain_jkbms cell voltage 4
  cell_voltage_5:
    name: pvbrain_jkbms cell voltage 5
  cell_voltage_6:
    name: pvbrain_jkbms cell voltage 6
  cell_voltage_7:
    name: pvbrain_jkbms cell voltage 7
  cell_voltage_8:
    name: pvbrain_jkbms cell voltage 8
  cell_voltage_9:
    name: pvbrain_jkbms cell voltage 9
  cell_voltage_10:
    name: pvbrain_jkbms cell voltage 10
  cell_voltage_11:
    name: pvbrain_jkbms cell voltage 11
  cell_voltage_12:
    name: pvbrain_jkbms cell voltage 12
  cell_voltage_13:
    name: pvbrain_jkbms cell voltage 13
  cell_voltage_14:
    name: pvbrain_jkbms cell voltage 14
  cell_voltage_15:
    name: pvbrain_jkbms cell voltage 15
  cell_voltage_16:
    name: pvbrain_jkbms cell voltage 16
  power_tube_temperature:
    name: pvbrain_jkbms power tube temperature
  temperature_sensor_1:
    name: pvbrain_jkbms temperature sensor 1
  temperature_sensor_2:
    name: pvbrain_jkbms temperature sensor 2
  total_voltage:
    name: pvbrain_jkbms total voltage
    id: pvbrain_jkbms_total_voltage
  current:
    name: pvbrain_jkbms current
    id: pvbrain_jkbms_current
  capacity_remaining:
    name: pvbrain_jkbms capacity remaining
    id: pvbrain_jkbms_capacity_remaining
  charging_cycles:
    name: pvbrain_jkbms charging cycles
  total_charging_cycle_capacity:
    name: pvbrain_jkbms total charging cycle capacity
  cell_voltage_overvoltage_protection:
    name: pvbrain_jkbms voltage overvoltage protection
  cell_voltage_overvoltage_recovery:
    name: pvbrain_jkbms voltage overvoltage recovery
  cell_voltage_overvoltage_delay:
    name: pvbrain_jkbms voltage overvoltage delay
  cell_voltage_undervoltage_protection:
    name: pvbrain_jkbms voltage undervoltage protection
  cell_voltage_undervoltage_recovery:
    name: pvbrain_jkbms voltage undervoltage recovery
  cell_voltage_undervoltage_delay:
    name: pvbrain_jkbms voltage undervoltage delay
  total_battery_capacity_setting:
    name: pvbrain_jkbms total battery capacity setting
    id: pvbrain_jkbms_total_battery_capacity_setting
`````

Was compiling fine until last dev (03/08/2022)

**Comment by syssi** [comment]
I would like to care about this issue as soon the new ESPHome version is released. The CI of this project does a daily build against the current release to make sure everything is in shape: https://github.com/syssi/esphome-jk-bms/actions

Another idea is to introduce a dev branch to work on the ESPhome dev compatibility already. So `dev` branch user could select `@dev` at the external components section.

**Comment by syssi** [comment]
Fixed at the main branc by 3eec9f25b65ea8ba126b24c6d1a3ca5f64d29719. Just try again! :-)

**Comment by SeByDocKy** [comment]
Super I will try .... :) the same problem fir pipsolar :(

**Comment by syssi** [comment]
Let's tackle this at my pipslar repo!

**Comment by SeByDocKy** [comment]
Ok the JKBMS part is now compiling :)
